# Generated by Django 3.1.7 on 2021-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.JSONField(null=True),
        ),
    ]
